name: Release Upload
description: Simple Github action to upload files to the current release
author: d1ceward
branding:
  icon: arrow-up-circle
  color: black
inputs:
  token:
    required: true
    description: |
      The GitHub access token which will be used to upload release artifacts.

      Usually this will be `secrets.GITHUB_TOKEN`.
  files:
    required: true
    description: |
      A list of files to publish, relative to the repository root.

      The files must be specified as a newline-delimited list of paths.

      ```yaml
      with:
        files: |
          bin/release-linux
          bin/release-windows
      ```
runs:
  using: node20
  main: dist/index.js
